// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IPhArrowLeft: typeof import('~icons/ph/arrow-left')['default']
    IPhEye: typeof import('~icons/ph/eye')['default']
    IPhEyeClosed: typeof import('~icons/ph/eye-closed')['default']
    IPhUser: typeof import('~icons/ph/user')['default']
    PageBuilderComponent: typeof import('./src/components/PageBuilderComponent.vue')['default']
  }
}

export { }
